{% set name = "tardis-sn" %}
{% set version_tag = "release-2021.07.01" %}

package:
  name: {{ name|lower }}
  version: {{ version_tag.replace('release-', '') }}

source:
  - url: https://github.com/tardis-sn/tardis/archive/{{ version_tag }}.tar.gz
    sha256: 0a1bbe02a03da255f9f916063090dd4f466e08e1289cedf541e73e1b6ef74b6b

build:
  number: 0
  skip: True  # [win or py != 37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - python =3.7
    - numpy =1.19
    - scipy =1.5
    - pandas =1.0
    - astropy =3
    - numba =0.53
    - numexpr
    - pyne =0.7=nomoab_openmc*
    - networkx
    - pygraphviz
    - pyyaml
    - jsonschema
    - pytables
    - h5py
    - pickle5
    - requests
    - tqdm
    - jupyter
    - matplotlib
    - ipywidgets
    - plotly
    - qgrid

test:
  imports:
    - tardis
  requires:
    - pytest
  commands:
    - pytest tardis

about:
  home: https://github.com/tardis-sn/tardis
  summary: TARDIS is a tool that creates synthetic observations (spectra) for exploding stars (supernovae).
  description: |
    TARDIS is an open-source Monte Carlo radiative-transfer spectral synthesis code for 1D models
    of supernova ejecta. It is designed for rapid spectral modelling of supernovae.
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  doc_url: https://tardis-sn.github.io/tardis
  dev_url: https://github.com/tardis-sn/tardis

extra:
  recipe-maintainers:
    - epassaro
    - wkerzendorf
