{% set name = "tardis-sn" %}
{% set version = "2022.12.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tardis-sn/tardis/archive/release-{{ version }}.tar.gz
    sha256: 5ec120d9f299c97c3f7d16bcfc6e761b975c36af7d9b78138046fe2c37ffc191

build:
  number: 0
  skip: true  # [win or py != 38]
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv  # workaround for https://github.com/pypa/setuptools_scm/issues/357

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python =3.8
    - numpy =1.19
    - scipy =1.5
    - pandas =1.0
    - astropy =5
    - numba =0.53
    - numexpr
    - radioactivedecay >=0.4.12
    - networkx
    - pygraphviz
    - pyyaml
    - jsonschema =3
    - pytables
    - h5py
    - requests
    - tqdm
    - notebook
    - matplotlib-base
    - ipywidgets
    - plotly
    - qgrid

test:
  imports:
    - tardis

about:
  home: https://github.com/tardis-sn/tardis
  summary: TARDIS is a tool that creates synthetic observations (spectra) for exploding stars (supernovae).
  description: |
    TARDIS is an open-source Monte Carlo radiative-transfer spectral synthesis code for 1D models
    of supernova ejecta. It is designed for rapid spectral modelling of supernovae.
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  doc_url: https://tardis-sn.github.io/tardis
  dev_url: https://github.com/tardis-sn/tardis

extra:
  recipe-maintainers:
    - epassaro
    - wkerzendorf
