{% set name = "tardis-sn" %}
{% set version_tag = "3.0.dev3384" %}

package:
  name: {{ name|lower }}
  version: {{ version_tag.replace('-alpha.', '.a') }}

source:
  - url: https://github.com/tardis-sn/tardis/archive/{{ version_tag }}.tar.gz
    sha256: a7f1404a279d5b60d4a961c53794abea10eec495ac4b9bb6d329482433a12b97
  - url: https://github.com/astropy/astropy-helpers/archive/v3.1.1.tar.gz
    sha256: 8ba7e693f1cc9a1c12be3b4ba9e65b67246bff1741c726b79a6dc7b233ba4cd4
    folder: astropy_helpers

build:
  number: 0
  skip: True  # [win or py<36]
  # A Python 3.7 build of pyne is not available
  skip: True  # [py==37]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - setuptools
    - astropy =3
    - cython >=0.29
    - numpy =1.15
    - pyne

  run:
    - python
    - astropy =3
    - numpy =1.15
    - scipy =1.1
    - pandas =0.24
    - numba =0.43
    - pyne
    - numexpr
    - networkx
    - pyyaml
    - jsonschema
    - pytables
    - h5py
    - requests
    - tqdm

test:
  imports:
    - tardis

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: TARDIS - Temperature And Radiative Diffusion In Supernovae
  home: https://github.com/tardis-sn/tardis
  dev_url: https://github.com/tardis-sn/tardis
  doc_url: https://tardis-sn.github.io/tardis

extra:
  recipe-maintainers:
    - epassaro
    - wkerzendorf
