{% set name = "tardis-sn" %}
{% set version = "2021.7.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/tardis-sn/tardis/archive/release-{{ version }}.tar.gz
    sha256: b764c56c01b244fc481dae8dd36537afa19420d16a315d6d2b67161903bbd1d6

build:
  number: 0
  skip: True  # [win or py != 37]
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . --no-deps -vv  # workaround for https://github.com/pypa/setuptools_scm/issues/357

requirements:
  host:
    - python
    - setuptools
    - setuptools_scm
    - pip

  run:
    - python =3.7
    - numpy =1.19
    - scipy =1.5
    - pandas =1.0
    - astropy =3
    - numba =0.53
    - numexpr
    - pyne =0.7=nomoab_openmc*
    - networkx
    - pygraphviz
    - pyyaml
    - jsonschema
    - pytables
    - h5py
    - pickle5
    - requests
    - tqdm
    - jupyter
    - matplotlib
    - ipywidgets
    - plotly
    - qgrid

test:
  imports:
    - tardis

about:
  home: https://github.com/tardis-sn/tardis
  summary: TARDIS is a tool that creates synthetic observations (spectra) for exploding stars (supernovae).
  description: |
    TARDIS is an open-source Monte Carlo radiative-transfer spectral synthesis code for 1D models
    of supernova ejecta. It is designed for rapid spectral modelling of supernovae.
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  doc_url: https://tardis-sn.github.io/tardis
  dev_url: https://github.com/tardis-sn/tardis

extra:
  recipe-maintainers:
    - epassaro
    - wkerzendorf
